"""initial

Revision ID: 7cba17190384
Revises:
Create Date: 2026-06-07 15:14:50.880740

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7cba17190384"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chess_borrowing_extension",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("prestamo_id", sa.Integer(), nullable=False),
        sa.Column("grado_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["grado_id"],
            ["grado.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prestamo_id"],
            ["prestamo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chess_borrowing_extension_prestamo_id"),
        "chess_borrowing_extension",
        ["prestamo_id"],
        unique=True,
    )
    op.create_table(
        "novedad",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("prestamo_id", sa.Integer(), nullable=False),
        sa.Column(
            "descripcion", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False
        ),
        sa.Column("resuelta", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prestamo_id"],
            ["prestamo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pago",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("matricula_id", sa.Integer(), nullable=False),
        sa.Column(
            "codigo_talonario",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("monto_total", sa.Integer(), nullable=False),
        sa.Column("fecha_pago", sa.DateTime(), nullable=False),
        sa.Column(
            "observacion", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["matricula_id"],
            ["matricula.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_talonario"),
    )
    op.create_table(
        "chess_novelty_extension",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("novedad_id", sa.Integer(), nullable=False),
        sa.Column("resuelta_por_id", sa.Integer(), nullable=True),
        sa.Column(
            "notas_resolucion",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["novedad_id"],
            ["novedad.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chess_novelty_extension_novedad_id"),
        "chess_novelty_extension",
        ["novedad_id"],
        unique=True,
    )
    op.create_table(
        "pagodetalle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("pago_id", sa.Integer(), nullable=False),
        sa.Column(
            "concepto", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("complementario_id", sa.Integer(), nullable=True),
        sa.Column("monto_aplicado", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complementario_id"],
            ["complementario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pago_id"],
            ["pago.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "auditoria", "fecha_accion", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.add_column("cafeteria", sa.Column("usuario_id", sa.Integer(), nullable=True))
    op.add_column(
        "cafeteria",
        sa.Column(
            "observaciones", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_cafeteria_estudiante_id"), "cafeteria", ["estudiante_id"], unique=False
    )
    op.create_index(
        op.f("ix_cafeteria_periodo_id"), "cafeteria", ["periodo_id"], unique=False
    )
    op.create_foreign_key(None, "cafeteria", "usuario", ["usuario_id"], ["id"])
    op.add_column(
        "detalleescuelaformacion", sa.Column("periodo_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "detalleescuelaformacion", sa.Column("usuario_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "detalleescuelaformacion",
        sa.Column("saldo_pendiente", sa.Integer(), nullable=False),
    )
    op.add_column(
        "detalleescuelaformacion",
        sa.Column(
            "motivo_retiro", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
    )
    op.add_column(
        "detalleescuelaformacion",
        sa.Column(
            "observaciones", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
    )
    op.add_column(
        "detalleescuelaformacion",
        sa.Column("valor_acordado", sa.Integer(), nullable=False),
    )
    op.add_column(
        "detalleescuelaformacion",
        sa.Column(
            "numero_comprobante",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_detalleescuelaformacion_estudiante_id"),
        "detalleescuelaformacion",
        ["estudiante_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detalleescuelaformacion_periodo_id"),
        "detalleescuelaformacion",
        ["periodo_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "detalleescuelaformacion", "periodo", ["periodo_id"], ["id"]
    )
    op.create_foreign_key(
        None, "detalleescuelaformacion", "usuario", ["usuario_id"], ["id"]
    )
    op.add_column(
        "detallepension", sa.Column("estudiante_id", sa.Integer(), nullable=False)
    )
    op.add_column("detallepension", sa.Column("cuota", sa.Integer(), nullable=False))
    op.add_column(
        "detallepension", sa.Column("valor_total", sa.Integer(), nullable=False)
    )
    op.add_column(
        "detallepension", sa.Column("valor_pagado", sa.Integer(), nullable=False)
    )
    op.add_column(
        "detallepension", sa.Column("fecha_pago", sa.DateTime(), nullable=False)
    )
    op.add_column("detallepension", sa.Column("faltante", sa.Boolean(), nullable=False))
    op.drop_constraint(
        op.f("detallepension_detalle_matricula_id_fkey"),
        "detallepension",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "detallepension", "estudiante", ["estudiante_id"], ["id"]
    )
    op.drop_column("detallepension", "detalle_matricula_id")
    op.add_column(
        "detalleprueba", sa.Column("valor_pagado", sa.Integer(), nullable=False)
    )
    op.add_column(
        "detalleprueba", sa.Column("periodo_id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "detalleprueba",
        "estado",
        existing_type=sa.BOOLEAN(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=20),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "detalleprueba", "periodo", ["periodo_id"], ["id"])
    op.drop_column("detalleprueba", "fecha_registro")
    op.add_column("grado", sa.Column("docente_titular_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "grado", "docente", ["docente_titular_id"], ["id"])
    op.add_column(
        "matricula", sa.Column("valor_pendiente_base", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "matricula",
        "estado_matricula",
        existing_type=sa.BOOLEAN(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=20),
        existing_nullable=False,
    )
    op.add_column("observador", sa.Column("docente_id", sa.Integer(), nullable=False))
    op.add_column("observador", sa.Column("esta_abierta", sa.Boolean(), nullable=False))
    op.add_column("observador", sa.Column("fecha_cierre", sa.DateTime(), nullable=True))
    op.create_foreign_key(None, "observador", "docente", ["docente_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_observador_docente_1", "observador", type_="foreignkey")
    op.drop_column("observador", "fecha_cierre")
    op.drop_column("observador", "esta_abierta")
    op.drop_column("observador", "docente_id")
    op.alter_column(
        "matricula",
        "estado_matricula",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
        type_=sa.BOOLEAN(),
        existing_nullable=False,
    )
    op.drop_column("matricula", "valor_pendiente_base")
    op.drop_constraint("fk_grado_docente_titular", "grado", type_="foreignkey")
    op.drop_column("grado", "docente_titular_id")
    op.add_column(
        "detalleprueba",
        sa.Column(
            "fecha_registro",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("fk_detalleprueba_periodo", "detalleprueba", type_="foreignkey")
    op.alter_column(
        "detalleprueba",
        "estado",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
        type_=sa.BOOLEAN(),
        existing_nullable=False,
    )
    op.drop_column("detalleprueba", "periodo_id")
    op.drop_column("detalleprueba", "valor_pagado")
    op.add_column(
        "detallepension",
        sa.Column(
            "detalle_matricula_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        "fk_detallepension_estudiante", "detallepension", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("detallepension_detalle_matricula_id_fkey"),
        "detallepension",
        "detallematricula",
        ["detalle_matricula_id"],
        ["id"],
    )
    op.drop_column("detallepension", "faltante")
    op.drop_column("detallepension", "fecha_pago")
    op.drop_column("detallepension", "valor_pagado")
    op.drop_column("detallepension", "valor_total")
    op.drop_column("detallepension", "cuota")
    op.drop_column("detallepension", "estudiante_id")
    op.drop_constraint(
        "fk_detalleescuelaformacion_periodo",
        "detalleescuelaformacion",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_detalleescuelaformacion_usuario",
        "detalleescuelaformacion",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_detalleescuelaformacion_periodo_id"),
        table_name="detalleescuelaformacion",
    )
    op.drop_index(
        op.f("ix_detalleescuelaformacion_estudiante_id"),
        table_name="detalleescuelaformacion",
    )
    op.drop_column("detalleescuelaformacion", "numero_comprobante")
    op.drop_column("detalleescuelaformacion", "valor_acordado")
    op.drop_column("detalleescuelaformacion", "observaciones")
    op.drop_column("detalleescuelaformacion", "motivo_retiro")
    op.drop_column("detalleescuelaformacion", "saldo_pendiente")
    op.drop_column("detalleescuelaformacion", "usuario_id")
    op.drop_column("detalleescuelaformacion", "periodo_id")
    op.drop_constraint("fk_cafeteria_usuario", "cafeteria", type_="foreignkey")
    op.drop_index(op.f("ix_cafeteria_periodo_id"), table_name="cafeteria")
    op.drop_index(op.f("ix_cafeteria_estudiante_id"), table_name="cafeteria")
    op.drop_column("cafeteria", "observaciones")
    op.drop_column("cafeteria", "usuario_id")
    op.alter_column(
        "auditoria",
        "fecha_accion",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_table("pagodetalle")
    op.drop_index(
        op.f("ix_chess_novelty_extension_novedad_id"),
        table_name="chess_novelty_extension",
    )
    op.drop_table("chess_novelty_extension")
    op.drop_table("pago")
    op.drop_table("novedad")
    op.drop_index(
        op.f("ix_chess_borrowing_extension_prestamo_id"),
        table_name="chess_borrowing_extension",
    )
    op.drop_table("chess_borrowing_extension")
    # ### end Alembic commands ###
